// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/shorten.proto

package shorten

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type URLType int32

const (
	URLType_RANDOM  URLType = 0
	URLType_DEFINED URLType = 1
)

var URLType_name = map[int32]string{
	0: "RANDOM",
	1: "DEFINED",
}

var URLType_value = map[string]int32{
	"RANDOM":  0,
	"DEFINED": 1,
}

func (x URLType) String() string {
	return proto.EnumName(URLType_name, int32(x))
}

func (URLType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0f306a479bff7799, []int{0}
}

type ShortenResponseStatus int32

const (
	ShortenResponseStatus_SUCCESS_SHORTEN     ShortenResponseStatus = 0
	ShortenResponseStatus_FAILED_SHORTEN      ShortenResponseStatus = 1
	ShortenResponseStatus_SLUG_ALREADY_EXISTS ShortenResponseStatus = 2
	ShortenResponseStatus_SAME_ORIGIN         ShortenResponseStatus = 3
)

var ShortenResponseStatus_name = map[int32]string{
	0: "SUCCESS_SHORTEN",
	1: "FAILED_SHORTEN",
	2: "SLUG_ALREADY_EXISTS",
	3: "SAME_ORIGIN",
}

var ShortenResponseStatus_value = map[string]int32{
	"SUCCESS_SHORTEN":     0,
	"FAILED_SHORTEN":      1,
	"SLUG_ALREADY_EXISTS": 2,
	"SAME_ORIGIN":         3,
}

func (x ShortenResponseStatus) String() string {
	return proto.EnumName(ShortenResponseStatus_name, int32(x))
}

func (ShortenResponseStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0f306a479bff7799, []int{1}
}

type ExpandResponseStatus int32

const (
	ExpandResponseStatus_SUCCESS_EXPAND ExpandResponseStatus = 0
	ExpandResponseStatus_NOT_FOUND      ExpandResponseStatus = 1
)

var ExpandResponseStatus_name = map[int32]string{
	0: "SUCCESS_EXPAND",
	1: "NOT_FOUND",
}

var ExpandResponseStatus_value = map[string]int32{
	"SUCCESS_EXPAND": 0,
	"NOT_FOUND":      1,
}

func (x ExpandResponseStatus) String() string {
	return proto.EnumName(ExpandResponseStatus_name, int32(x))
}

func (ExpandResponseStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0f306a479bff7799, []int{2}
}

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

var HealthCheckResponse_ServingStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SERVING",
	2: "NOT_SERVING",
}

var HealthCheckResponse_ServingStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"SERVING":     1,
	"NOT_SERVING": 2,
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return proto.EnumName(HealthCheckResponse_ServingStatus_name, int32(x))
}

func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0f306a479bff7799, []int{5, 0}
}

type ShortURL struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               uint64   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Base                 uint64   `protobuf:"varint,3,opt,name=base,proto3" json:"base,omitempty"`
	Origin               string   `protobuf:"bytes,4,opt,name=origin,proto3" json:"origin,omitempty"`
	Slug                 string   `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug,omitempty"`
	UrlType              URLType  `protobuf:"varint,6,opt,name=url_type,json=urlType,proto3,enum=shorten.URLType" json:"url_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShortURL) Reset()         { *m = ShortURL{} }
func (m *ShortURL) String() string { return proto.CompactTextString(m) }
func (*ShortURL) ProtoMessage()    {}
func (*ShortURL) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f306a479bff7799, []int{0}
}

func (m *ShortURL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortURL.Unmarshal(m, b)
}
func (m *ShortURL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortURL.Marshal(b, m, deterministic)
}
func (m *ShortURL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortURL.Merge(m, src)
}
func (m *ShortURL) XXX_Size() int {
	return xxx_messageInfo_ShortURL.Size(m)
}
func (m *ShortURL) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortURL.DiscardUnknown(m)
}

var xxx_messageInfo_ShortURL proto.InternalMessageInfo

func (m *ShortURL) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ShortURL) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ShortURL) GetBase() uint64 {
	if m != nil {
		return m.Base
	}
	return 0
}

func (m *ShortURL) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *ShortURL) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *ShortURL) GetUrlType() URLType {
	if m != nil {
		return m.UrlType
	}
	return URLType_RANDOM
}

type ShortenResponse struct {
	Slug                 string                `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Status               ShortenResponseStatus `protobuf:"varint,2,opt,name=status,proto3,enum=shorten.ShortenResponseStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ShortenResponse) Reset()         { *m = ShortenResponse{} }
func (m *ShortenResponse) String() string { return proto.CompactTextString(m) }
func (*ShortenResponse) ProtoMessage()    {}
func (*ShortenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f306a479bff7799, []int{1}
}

func (m *ShortenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortenResponse.Unmarshal(m, b)
}
func (m *ShortenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortenResponse.Marshal(b, m, deterministic)
}
func (m *ShortenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortenResponse.Merge(m, src)
}
func (m *ShortenResponse) XXX_Size() int {
	return xxx_messageInfo_ShortenResponse.Size(m)
}
func (m *ShortenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShortenResponse proto.InternalMessageInfo

func (m *ShortenResponse) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *ShortenResponse) GetStatus() ShortenResponseStatus {
	if m != nil {
		return m.Status
	}
	return ShortenResponseStatus_SUCCESS_SHORTEN
}

type ExpandRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExpandRequest) Reset()         { *m = ExpandRequest{} }
func (m *ExpandRequest) String() string { return proto.CompactTextString(m) }
func (*ExpandRequest) ProtoMessage()    {}
func (*ExpandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f306a479bff7799, []int{2}
}

func (m *ExpandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpandRequest.Unmarshal(m, b)
}
func (m *ExpandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpandRequest.Marshal(b, m, deterministic)
}
func (m *ExpandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpandRequest.Merge(m, src)
}
func (m *ExpandRequest) XXX_Size() int {
	return xxx_messageInfo_ExpandRequest.Size(m)
}
func (m *ExpandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExpandRequest proto.InternalMessageInfo

func (m *ExpandRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type ExpandResponse struct {
	ShortURL             *ShortURL            `protobuf:"bytes,1,opt,name=shortURL,proto3" json:"shortURL,omitempty"`
	Status               ExpandResponseStatus `protobuf:"varint,2,opt,name=status,proto3,enum=shorten.ExpandResponseStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ExpandResponse) Reset()         { *m = ExpandResponse{} }
func (m *ExpandResponse) String() string { return proto.CompactTextString(m) }
func (*ExpandResponse) ProtoMessage()    {}
func (*ExpandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f306a479bff7799, []int{3}
}

func (m *ExpandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpandResponse.Unmarshal(m, b)
}
func (m *ExpandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpandResponse.Marshal(b, m, deterministic)
}
func (m *ExpandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpandResponse.Merge(m, src)
}
func (m *ExpandResponse) XXX_Size() int {
	return xxx_messageInfo_ExpandResponse.Size(m)
}
func (m *ExpandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExpandResponse proto.InternalMessageInfo

func (m *ExpandResponse) GetShortURL() *ShortURL {
	if m != nil {
		return m.ShortURL
	}
	return nil
}

func (m *ExpandResponse) GetStatus() ExpandResponseStatus {
	if m != nil {
		return m.Status
	}
	return ExpandResponseStatus_SUCCESS_EXPAND
}

type HealthCheckRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckRequest) Reset()         { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()    {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f306a479bff7799, []int{4}
}

func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(m, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

func (m *HealthCheckRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type HealthCheckResponse struct {
	Status               HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=shorten.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f306a479bff7799, []int{5}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if m != nil {
		return m.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func init() {
	proto.RegisterEnum("shorten.URLType", URLType_name, URLType_value)
	proto.RegisterEnum("shorten.ShortenResponseStatus", ShortenResponseStatus_name, ShortenResponseStatus_value)
	proto.RegisterEnum("shorten.ExpandResponseStatus", ExpandResponseStatus_name, ExpandResponseStatus_value)
	proto.RegisterEnum("shorten.HealthCheckResponse_ServingStatus", HealthCheckResponse_ServingStatus_name, HealthCheckResponse_ServingStatus_value)
	proto.RegisterType((*ShortURL)(nil), "shorten.ShortURL")
	proto.RegisterType((*ShortenResponse)(nil), "shorten.ShortenResponse")
	proto.RegisterType((*ExpandRequest)(nil), "shorten.ExpandRequest")
	proto.RegisterType((*ExpandResponse)(nil), "shorten.ExpandResponse")
	proto.RegisterType((*HealthCheckRequest)(nil), "shorten.HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "shorten.HealthCheckResponse")
}

func init() { proto.RegisterFile("proto/shorten.proto", fileDescriptor_0f306a479bff7799) }

var fileDescriptor_0f306a479bff7799 = []byte{
	// 538 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0xcd, 0x92, 0xc4, 0x26, 0x83, 0x00, 0x77, 0x68, 0x83, 0x95, 0x7e, 0x08, 0xb9, 0x17, 0x44,
	0x55, 0x2a, 0x51, 0x35, 0x52, 0x7a, 0x73, 0xb0, 0x21, 0x56, 0x1d, 0xbb, 0xda, 0xc5, 0x6d, 0x7a,
	0xa8, 0x2c, 0x12, 0x56, 0xe0, 0x16, 0x01, 0xf5, 0x47, 0xd4, 0xfc, 0x90, 0xde, 0xfb, 0x53, 0xfa,
	0xd3, 0x2a, 0x2f, 0xb6, 0x55, 0x08, 0xe9, 0x6d, 0x66, 0xf6, 0xcd, 0x7b, 0xcf, 0xfb, 0x56, 0x86,
	0xc6, 0x2a, 0x5c, 0xc6, 0xcb, 0x37, 0xd1, 0x6c, 0x19, 0xc6, 0x7c, 0xd1, 0x15, 0x1d, 0xca, 0x59,
	0xab, 0xfd, 0x26, 0x50, 0x66, 0x69, 0xed, 0x51, 0x1b, 0x6b, 0x50, 0x0a, 0x26, 0x2a, 0x69, 0x91,
	0xf6, 0x01, 0x2d, 0x05, 0x13, 0x6c, 0x82, 0x9c, 0x44, 0x3c, 0xf4, 0x83, 0x89, 0x5a, 0x12, 0x43,
	0x29, 0x6d, 0xad, 0x09, 0x22, 0x1c, 0x5c, 0x8f, 0x23, 0xae, 0xee, 0x8b, 0xa9, 0xa8, 0xf1, 0x18,
	0xa4, 0x65, 0x18, 0x4c, 0x83, 0x85, 0x7a, 0xd0, 0x22, 0xed, 0x23, 0x9a, 0x75, 0x29, 0x36, 0x9a,
	0x27, 0x53, 0xf5, 0x50, 0x4c, 0x45, 0x8d, 0xaf, 0xa0, 0x9c, 0x84, 0x73, 0x3f, 0xbe, 0x5b, 0x71,
	0x55, 0x6a, 0x91, 0x76, 0xad, 0xa7, 0x74, 0x73, 0x83, 0x1e, 0xb5, 0x47, 0x77, 0x2b, 0x4e, 0xe5,
	0x24, 0x9c, 0xa7, 0x85, 0xf6, 0x15, 0xea, 0x6c, 0x7d, 0x46, 0x79, 0xb4, 0x5a, 0x2e, 0x22, 0x5e,
	0x70, 0x92, 0x7f, 0x38, 0x4f, 0x41, 0x8a, 0xe2, 0x71, 0x9c, 0x44, 0xc2, 0x6b, 0xad, 0xf7, 0xa2,
	0x60, 0xdc, 0xda, 0x66, 0x02, 0x45, 0x33, 0xb4, 0xf6, 0x12, 0xaa, 0xe6, 0xcf, 0xd5, 0x78, 0x31,
	0xa1, 0xfc, 0x47, 0xc2, 0xa3, 0x78, 0x17, 0xb9, 0x76, 0x0b, 0xb5, 0x1c, 0x94, 0x59, 0x78, 0x0d,
	0xe5, 0x28, 0xbb, 0x37, 0x81, 0xac, 0xf4, 0x1e, 0x6d, 0x0a, 0x7a, 0xd4, 0xa6, 0x05, 0x04, 0xdf,
	0x6d, 0xb9, 0x7b, 0x5e, 0x80, 0x37, 0x79, 0xb7, 0xcc, 0x75, 0x01, 0x2f, 0xf8, 0x78, 0x1e, 0xcf,
	0xfa, 0x33, 0x7e, 0xf3, 0x3d, 0x77, 0xa8, 0x82, 0x1c, 0xf1, 0xf0, 0x36, 0xb8, 0xe1, 0x99, 0xc9,
	0xbc, 0xd5, 0x7e, 0x11, 0x68, 0x6c, 0x2c, 0x64, 0x6e, 0xcf, 0x0b, 0x79, 0x22, 0xe4, 0x3b, 0x85,
	0xfc, 0x0e, 0x74, 0x97, 0xa5, 0x6c, 0x8b, 0xe9, 0x96, 0x97, 0xf7, 0x50, 0xdd, 0x38, 0xc0, 0x0a,
	0xc8, 0x9e, 0xf3, 0xc1, 0x71, 0x3f, 0x3b, 0xca, 0x5e, 0xda, 0x30, 0x93, 0x7e, 0xb2, 0x9c, 0xa1,
	0x42, 0xb0, 0x0e, 0x15, 0xc7, 0x1d, 0xf9, 0xf9, 0xa0, 0xd4, 0xd1, 0x40, 0xce, 0x72, 0x45, 0x00,
	0x89, 0xea, 0x8e, 0xe1, 0x5e, 0xae, 0x97, 0x0c, 0x73, 0x60, 0x39, 0xa6, 0xa1, 0x90, 0xce, 0x37,
	0x78, 0xb2, 0x33, 0x29, 0x6c, 0x40, 0x9d, 0x79, 0xfd, 0xbe, 0xc9, 0x98, 0xcf, 0x2e, 0x5c, 0x3a,
	0x32, 0x53, 0x3d, 0x84, 0xda, 0x40, 0xb7, 0x6c, 0xd3, 0x28, 0x66, 0x04, 0x9b, 0xd0, 0x60, 0xb6,
	0x37, 0xf4, 0x75, 0x9b, 0x9a, 0xba, 0xf1, 0xc5, 0x37, 0xaf, 0x2c, 0x36, 0x62, 0x4a, 0x29, 0xf5,
	0xc3, 0xf4, 0x4b, 0xd3, 0x77, 0xa9, 0x35, 0xb4, 0x1c, 0x65, 0xbf, 0x73, 0x06, 0x8f, 0x77, 0xdd,
	0x7b, 0xca, 0x9a, 0x4b, 0x99, 0x57, 0x1f, 0x75, 0xc7, 0x50, 0xf6, 0xb0, 0x0a, 0x47, 0xe9, 0xc7,
	0x0c, 0x5c, 0xcf, 0x31, 0x14, 0xd2, 0xfb, 0x43, 0x40, 0x66, 0xeb, 0xeb, 0xc6, 0x53, 0x90, 0x33,
	0xcb, 0x78, 0x3f, 0xfd, 0x13, 0xf5, 0xa1, 0x17, 0x88, 0x67, 0x20, 0xad, 0xe5, 0xf1, 0xf8, 0xde,
	0x3b, 0x10, 0x11, 0x9f, 0x34, 0x1f, 0x78, 0x1f, 0x78, 0x0e, 0x87, 0x22, 0x2c, 0x7c, 0xba, 0x3b,
	0xc2, 0xf5, 0xfa, 0xb3, 0xff, 0xe5, 0x7b, 0x2d, 0x89, 0x9f, 0xc0, 0xdb, 0xbf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x09, 0xc0, 0x36, 0x23, 0x1b, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	Shorten(ctx context.Context, in *ShortURL, opts ...grpc.CallOption) (*ShortenResponse, error)
	Expand(ctx context.Context, in *ExpandRequest, opts ...grpc.CallOption) (*ExpandResponse, error)
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Shorten(ctx context.Context, in *ShortURL, opts ...grpc.CallOption) (*ShortenResponse, error) {
	out := new(ShortenResponse)
	err := c.cc.Invoke(ctx, "/shorten.Service/Shorten", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Expand(ctx context.Context, in *ExpandRequest, opts ...grpc.CallOption) (*ExpandResponse, error) {
	out := new(ExpandResponse)
	err := c.cc.Invoke(ctx, "/shorten.Service/Expand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/shorten.Service/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	Shorten(context.Context, *ShortURL) (*ShortenResponse, error)
	Expand(context.Context, *ExpandRequest) (*ExpandResponse, error)
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Shorten_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortURL)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Shorten(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shorten.Service/Shorten",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Shorten(ctx, req.(*ShortURL))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Expand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Expand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shorten.Service/Expand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Expand(ctx, req.(*ExpandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shorten.Service/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shorten.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Shorten",
			Handler:    _Service_Shorten_Handler,
		},
		{
			MethodName: "Expand",
			Handler:    _Service_Expand_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _Service_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/shorten.proto",
}
